name: surf2sawa
description: "Website for users to pay their S2S bills"

publish_to: 'none'

version: 1.0.0+22

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  intl: ^0.18.1
  pin_input_text_field: '4.5.1'
  pretty_http_logger: ^1.0.4
  rxdart: ^0.27.7
  shared_preferences: ^2.0.6
  syncfusion_flutter_gauges: 25.1.35
  url_strategy: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
    - assets/icons/
    - assets/ui/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-100.ttf
          weight: 100
        - asset: fonts/Poppins/Poppins-100-Italic.ttf
          weight: 100
          style: italic
        - asset: fonts/Poppins/Poppins-200.ttf
          weight: 200
        - asset: fonts/Poppins/Poppins-200-Italic.ttf
          weight: 200
          style: italic
        - asset: fonts/Poppins/Poppins-300.ttf
          weight: 300
        - asset: fonts/Poppins/Poppins-300-Italic.ttf
          weight: 300
          style: italic
        - asset: fonts/Poppins/Poppins-400.ttf
          weight: 400
        - asset: fonts/Poppins/Poppins-400-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Poppins/Poppins-500.ttf
          weight: 500
        - asset: fonts/Poppins/Poppins-500-Italic.ttf
          weight: 500
          style: italic
        - asset: fonts/Poppins/Poppins-600.ttf
          weight: 600
        - asset: fonts/Poppins/Poppins-600-Italic.ttf
          weight: 600
          style: italic
        - asset: fonts/Poppins/Poppins-700.ttf
          weight: 700
        - asset: fonts/Poppins/Poppins-700-Italic.ttf
          weight: 700
          style: italic
        - asset: fonts/Poppins/Poppins-800.ttf
          weight: 800
        - asset: fonts/Poppins/Poppins-800-Italic.ttf
          weight: 800
          style: italic
        - asset: fonts/Poppins/Poppins-900.ttf
          weight: 900
        - asset: fonts/Poppins/Poppins-900-Italic.ttf
          weight: 900
          style: italic
    - family: Nunito
      fonts:
        - asset: fonts/Nunito/Nunito-200.ttf
          weight: 200
        - asset: fonts/Nunito/Nunito-200-Italic.ttf
          weight: 200
          style: italic
        - asset: fonts/Nunito/Nunito-300.ttf
          weight: 300
        - asset: fonts/Nunito/Nunito-300-Italic.ttf
          weight: 300
          style: italic
        - asset: fonts/Nunito/Nunito-400.ttf
          weight: 400
        - asset: fonts/Nunito/Nunito-400-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Nunito/Nunito-500.ttf
          weight: 500
        - asset: fonts/Nunito/Nunito-500-Italic.ttf
          weight: 500
          style: italic
        - asset: fonts/Nunito/Nunito-600.ttf
          weight: 600
        - asset: fonts/Nunito/Nunito-600-Italic.ttf
          weight: 600
          style: italic
        - asset: fonts/Nunito/Nunito-700.ttf
          weight: 700
        - asset: fonts/Nunito/Nunito-700-Italic.ttf
          weight: 700
          style: italic
        - asset: fonts/Nunito/Nunito-800.ttf
          weight: 800
        - asset: fonts/Nunito/Nunito-800-Italic.ttf
          weight: 800
          style: italic
        - asset: fonts/Nunito/Nunito-900.ttf
          weight: 900
        - asset: fonts/Nunito/Nunito-900-Italic.ttf
          weight: 900
          style: italic
    - family: Work Sans
      fonts:
        - asset: fonts/WorkSans/WorkSans-100.ttf
          weight: 100
        - asset: fonts/WorkSans/WorkSans-100-Italic.ttf
          weight: 100
          style: italic
        - asset: fonts/WorkSans/WorkSans-200.ttf
          weight: 200
        - asset: fonts/WorkSans/WorkSans-200-Italic.ttf
          weight: 200
          style: italic
        - asset: fonts/WorkSans/WorkSans-300.ttf
          weight: 300
        - asset: fonts/WorkSans/WorkSans-300-Italic.ttf
          weight: 300
          style: italic
        - asset: fonts/WorkSans/WorkSans-400.ttf
          weight: 400
        - asset: fonts/WorkSans/WorkSans-400-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/WorkSans/WorkSans-500.ttf
          weight: 500
        - asset: fonts/WorkSans/WorkSans-500-Italic.ttf
          weight: 500
          style: italic
        - asset: fonts/WorkSans/WorkSans-600.ttf
          weight: 600
        - asset: fonts/WorkSans/WorkSans-600-Italic.ttf
          weight: 600
          style: italic
        - asset: fonts/WorkSans/WorkSans-700.ttf
          weight: 700
        - asset: fonts/WorkSans/WorkSans-700-Italic.ttf
          weight: 700
          style: italic
        - asset: fonts/WorkSans/WorkSans-800.ttf
          weight: 800
        - asset: fonts/WorkSans/WorkSans-800-Italic.ttf
          weight: 800
          style: italic
        - asset: fonts/WorkSans/WorkSans-900.ttf
          weight: 900
        - asset: fonts/WorkSans/WorkSans-900-Italic.ttf
          weight: 900
          style: italic
  uses-material-design: true
