name: s2s_after_sales
description: "Website for users to pay their S2S bills"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+7

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  intl: ^0.18.1
  pin_input_text_field: '4.5.1'
  pretty_http_logger: ^1.0.4
  rxdart: ^0.27.7
  shared_preferences: ^2.0.6
  url_strategy: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-100.ttf
          weight: 100
        - asset: fonts/Poppins/Poppins-100-Italic.ttf
          weight: 100
          style: italic
        - asset: fonts/Poppins/Poppins-200.ttf
          weight: 200
        - asset: fonts/Poppins/Poppins-200-Italic.ttf
          weight: 200
          style: italic
        - asset: fonts/Poppins/Poppins-300.ttf
          weight: 300
        - asset: fonts/Poppins/Poppins-300-Italic.ttf
          weight: 300
          style: italic
        - asset: fonts/Poppins/Poppins-400.ttf
          weight: 400
        - asset: fonts/Poppins/Poppins-400-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Poppins/Poppins-500.ttf
          weight: 500
        - asset: fonts/Poppins/Poppins-500-Italic.ttf
          weight: 500
          style: italic
        - asset: fonts/Poppins/Poppins-600.ttf
          weight: 600
        - asset: fonts/Poppins/Poppins-600-Italic.ttf
          weight: 600
          style: italic
        - asset: fonts/Poppins/Poppins-700.ttf
          weight: 700
        - asset: fonts/Poppins/Poppins-700-Italic.ttf
          weight: 700
          style: italic
        - asset: fonts/Poppins/Poppins-800.ttf
          weight: 800
        - asset: fonts/Poppins/Poppins-800-Italic.ttf
          weight: 800
          style: italic
        - asset: fonts/Poppins/Poppins-900.ttf
          weight: 900
        - asset: fonts/Poppins/Poppins-900-Italic.ttf
          weight: 900
          style: italic
  uses-material-design: true
